### ISSUE TITLE
Question about Distance Map

### ISSUE THREAD

**Issue by hhuang-code** [collinarnett/protein_gan#24]
Hi Collin,

Thanks for your implementation of the GAN for protein generation!

I have a question regarding the distance map in the data_generation.ipynb: 
answer[row, col] = residue_one["CA"] - residue_two["CA"]

My personal understanding is: answer[row, col] = norm(residue_one["CA"] - residue_two["CA"])

I'm not sure which one is correct... Could you kindly look into this? Thank you!

**Comment by collinarnett** [comment]
I haven't worked on this repository in two years. I you want to look into this feel free; however I have moved on to other projects.
